version: "3.8"

services:
  app:
    container_name: react-docker-practice-prod
    build:
      context: .
      dockerfile: prod.Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - 80:80
    stdin_open: true
    tty: true
